-- Add home layout config to SiteConfig
ALTER TABLE `SiteConfig`
  ADD COLUMN `homeSectionOrder` VARCHAR(191) NOT NULL DEFAULT 'TRENDING,BOOSTED,CONTINUE_WATCHING,COMMUNITY,RECENT',
  ADD COLUMN `homeCategoryIds` VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN `homeSectionLimit` INT NOT NULL DEFAULT 12;
